version: '2'

services:
  base:
    build:
      context: .
      dockerfile: Dockerfile
    user: app
    env_file:
      - backend.env
    environment:
      - PYTHONUNBUFFERED=1
      - PYTHONDONTWRITEBYTECODE=1
      - DATABASE_URL=postgres://postgres@db/postgres
      - DEBUG=True
      - SECRET_KEY=59114b6a-2858-4caf-8878-482a24ee9542
      - DJANGO_LOG_LEVEL=DEBUG
      - DJANGO_LOG_FORMAT=json
      - DJANGO_SETTINGS_MODULE=backend.settings.local

  # This `app` service is used for testing with no volumes mounted.
  app:
    extends:
      service: base
    depends_on:
      - db
    links:
      - db
    command: "true"

  server:
    extends:
      service: base
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    depends_on:
      - db
    links:
      - db
    command: dev

  db:
    image: postgres:9.5.12
