version: 2
jobs:
  build:
    docker:
      - image: docker/compose:1.21.2
    steps:
      - setup_remote_docker

      - checkout

      # Copy an empty .env file since it is referenced in the docker-compose file.
      - run: cp backend.env.dist backend.env

      - run: docker-compose run app flake8 backend

      # TODO: Add code coverage.
      - run: docker-compose run app python manage.py test
