version: 2
jobs:
  build:
    docker:
      - image: circleci/node:8.6.0

    working_directory: ~/repo

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-

      - run: yarn

      # These steps are needed for any repository with a lockfile.
      # https://github.com/greenkeeperio/greenkeeper-lockfile
      - run: yarn global add greenkeeper-lockfile
      - run: greenkeeper-lockfile-update
      - run: greenkeeper-lockfile-upload

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      # run tests!
      - run: yarn test
